spring:
  devtools:
    # Auto Restart
    restart:
      enabled: true
      additional-exclude: static/**,public/**
      # Live Reload
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/loginPractice
    username: sa
    password:

  jpa:
    database: h2
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083


