# Generated by Django 4.2 on 2023-05-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_id',
            field=models.CharField(max_length=32, verbose_name='아이디'),
        ),
    ]
